import { Servicio } from '@/types';

export const MOCK_SERVICIOS: Servicio[] = [
  {
    id: '1',
    categoriaId: '3',
    categoriaNombre: 'Spotify',
    nombre: 'Spotify - Familiar',
    tipo: 'familiar',
    correo: 'SpotifySrvCliente10@gmail.com',
    contrasena: 'Password123!',
    perfilesDisponibles: 6,
    perfilesOcupados: 5,
    costoPorPerfil: 4.00,
    costoTotal: 24.00,
    activo: true,
    renovacionAutomatica: true,
    fechaRenovacion: new Date('2026-02-15'),
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2026-01-28'),
    createdBy: '1'
  },
  {
    id: '2',
    categoriaId: '1',
    categoriaNombre: 'Netflix',
    nombre: 'Netflix - Premium',
    tipo: 'familiar',
    correo: 'netflix.premium01@gmail.com',
    contrasena: 'NetPass456!',
    perfilesDisponibles: 4,
    perfilesOcupados: 3,
    costoPorPerfil: 5.00,
    costoTotal: 20.00,
    activo: true,
    renovacionAutomatica: true,
    fechaRenovacion: new Date('2026-02-10'),
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2026-01-28'),
    createdBy: '1'
  },
  {
    id: '3',
    categoriaId: '4',
    categoriaNombre: 'Crunchyroll',
    nombre: 'Crunchyroll - Mega Fan',
    tipo: 'individual',
    correo: 'crunchyroll.fan@gmail.com',
    contrasena: 'AnimePass789!',
    perfilesDisponibles: 1,
    perfilesOcupados: 1,
    costoPorPerfil: 8.00,
    costoTotal: 8.00,
    activo: true,
    renovacionAutomatica: false,
    fechaRenovacion: new Date('2026-03-01'),
    createdAt: new Date('2025-01-05'),
    updatedAt: new Date('2026-01-28'),
    createdBy: '1'
  },
  {
    id: '4',
    categoriaId: '2',
    categoriaNombre: 'Disney Plus',
    nombre: 'Disney Plus - Familiar',
    tipo: 'familiar',
    correo: 'disney.family@gmail.com',
    contrasena: 'Disney2024!',
    perfilesDisponibles: 7,
    perfilesOcupados: 4,
    costoPorPerfil: 3.50,
    costoTotal: 14.00,
    activo: true,
    renovacionAutomatica: true,
    fechaRenovacion: new Date('2026-02-20'),
    createdAt: new Date('2025-01-01'),
    updatedAt: new Date('2026-01-28'),
    createdBy: '1'
  },
  {
    id: '5',
    categoriaId: '5',
    categoriaNombre: 'YouTube Premium',
    nombre: 'YouTube Premium - Familiar',
    tipo: 'familiar',
    correo: 'youtube.premium@gmail.com',
    contrasena: 'YtPass123!',
    perfilesDisponibles: 5,
    perfilesOcupados: 2,
    costoPorPerfil: 4.50,
    costoTotal: 22.50,
    activo: true,
    renovacionAutomatica: true,
    fechaRenovacion: new Date('2026-02-25'),
    createdAt: new Date('2025-01-10'),
    updatedAt: new Date('2026-01-28'),
    createdBy: '1'
  }
];
