import { Suscripcion } from '@/types';

export const MOCK_SUSCRIPCIONES: Suscripcion[] = [
  {
    id: '1',
    clienteId: '1',
    clienteNombre: 'Israel Williams',
    tipo: 'cliente',
    servicioId: '1',
    servicioNombre: 'Spotify - Familiar',
    categoriaId: '3',
    categoriaNombre: 'Spotify',
    correo: 'SpotifySrvCliente10@gmail.com',
    contrasena: 'Password123!',
    monto: 4.00,
    moneda: 'USD',
    metodoPagoId: '1',
    metodoPagoNombre: 'Yappy - Allan',
    cicloPago: 'mensual',
    fechaInicio: new Date('2026-01-22'),
    fechaVencimiento: new Date('2026-02-22'),
    renovaciones: 0,
    consumoPorcentaje: 20,
    montoRestante: 3.20,
    estado: 'activa',
    notificado: false,
    createdAt: new Date('2026-01-22'),
    updatedAt: new Date('2026-01-28'),
    createdBy: '1'
  },
  {
    id: '2',
    clienteId: '2',
    clienteNombre: 'Jonathan Mendoza',
    tipo: 'cliente',
    servicioId: '2',
    servicioNombre: 'Netflix - Premium',
    categoriaId: '1',
    categoriaNombre: 'Netflix',
    correo: 'netflix.premium01@gmail.com',
    contrasena: 'NetPass456!',
    monto: 5.00,
    moneda: 'USD',
    metodoPagoId: '1',
    metodoPagoNombre: 'Yappy - Allan',
    cicloPago: 'mensual',
    fechaInicio: new Date('2026-01-15'),
    fechaVencimiento: new Date('2026-02-15'),
    renovaciones: 1,
    consumoPorcentaje: 45,
    montoRestante: 2.75,
    estado: 'activa',
    notificado: false,
    createdAt: new Date('2026-01-15'),
    updatedAt: new Date('2026-01-28'),
    createdBy: '1'
  },
  {
    id: '3',
    clienteId: '3',
    clienteNombre: 'Angeline Quintero',
    tipo: 'cliente',
    servicioId: '3',
    servicioNombre: 'Crunchyroll - Mega Fan',
    categoriaId: '4',
    categoriaNombre: 'Crunchyroll',
    correo: 'crunchyroll.fan@gmail.com',
    contrasena: 'AnimePass789!',
    monto: 8.00,
    moneda: 'USD',
    metodoPagoId: '2',
    metodoPagoNombre: 'Banco Nacional - Ahorro',
    cicloPago: 'mensual',
    fechaInicio: new Date('2025-09-15'),
    fechaVencimiento: new Date('2025-10-15'),
    renovaciones: 4,
    consumoPorcentaje: 100,
    montoRestante: 0,
    estado: 'vencida',
    notificado: true,
    diasRetraso: 105,
    createdAt: new Date('2025-09-15'),
    updatedAt: new Date('2026-01-28'),
    createdBy: '1'
  },
  {
    id: '4',
    clienteId: '4',
    clienteNombre: 'Carlos Jiménez',
    tipo: 'cliente',
    servicioId: '4',
    servicioNombre: 'Disney Plus - Familiar',
    categoriaId: '2',
    categoriaNombre: 'Disney Plus',
    correo: 'disney.family@gmail.com',
    contrasena: 'Disney2024!',
    monto: 3.50,
    moneda: 'USD',
    metodoPagoId: '1',
    metodoPagoNombre: 'Yappy - Allan',
    cicloPago: 'mensual',
    fechaInicio: new Date('2026-01-10'),
    fechaVencimiento: new Date('2026-02-10'),
    renovaciones: 0,
    consumoPorcentaje: 60,
    montoRestante: 1.40,
    estado: 'activa',
    notificado: false,
    createdAt: new Date('2026-01-10'),
    updatedAt: new Date('2026-01-28'),
    createdBy: '1'
  },
  {
    id: '5',
    revendedorId: '1',
    revendedorNombre: 'Pedro Distribuciones',
    tipo: 'revendedor',
    servicioId: '5',
    servicioNombre: 'YouTube Premium - Familiar',
    categoriaId: '5',
    categoriaNombre: 'YouTube Premium',
    correo: 'youtube.premium@gmail.com',
    contrasena: 'YtPass123!',
    monto: 4.50,
    moneda: 'USD',
    metodoPagoId: '2',
    metodoPagoNombre: 'Banco Nacional - Ahorro',
    cicloPago: 'mensual',
    fechaInicio: new Date('2026-01-20'),
    fechaVencimiento: new Date('2026-02-20'),
    renovaciones: 0,
    consumoPorcentaje: 25,
    montoRestante: 3.375,
    estado: 'activa',
    notificado: false,
    createdAt: new Date('2026-01-20'),
    updatedAt: new Date('2026-01-28'),
    createdBy: '1'
  }
];
